language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  coverage run -m unittest discover -s tests -p "test_*.py"
branches:
  only:
  - master
after_success:
  coveralls
